# Generated by Django 5.2 on 2025-10-06 07:27

import cvs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='cvs/', validators=[cvs.models.validate_file_extension]),
        ),
    ]
