# Generated by Django 5.2 on 2025-10-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cvs', '0002_cv_extracted_text_alter_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='industry_category',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='processed_text',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='years_of_experience',
        ),
    ]
