# Generated by Django 5.2.7 on 2025-10-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cvs', '0003_remove_cv_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting_text', 'Extracting Text'), ('analyzing_skills', 'Analyzing Skills'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='status_message',
            field=models.TextField(blank=True),
        ),
    ]
